branches:
  only:
    - integration
    - /-ci$/
    - /-cit$/

os: linux
dist: bionic

language: c

jobs:
  # Run unit tests that provide wide coverage on multiple architectures.
  include:
    # Valgrind is disabled due to some platform-specific issues in getpwuid() and getgrgid() that do not seem to be pgBackRest bugs.
    - arch: ppc64le
      env:
        - PGB_CI="test --vm=none --param=no-coverage --param=module=command --param=module=storage --param=no-valgrind"
      services:

    - arch: arm64
      env:
        - PGB_CI="test --vm=none --param=no-coverage --param=module=command --param=module=storage"
      services:

    - arch: s390x
      env:
        - PGB_CI="test --vm=none --param=no-coverage --param=module=command --param=module=storage"
      services:

install:
  - umask 0022 && cd ~ && pwd && whoami && umask && groups
  - df -Th && top -bn1

script:
  - ${TRAVIS_BUILD_DIR?}/test/ci.pl ${PGB_CI?}
